
baseurl = "https://heider.design"
copyright = "© Nicolas Heider"
enablerobotstxt = true
DefaultContentLanguage = "de"

hasCJKLanguage = true


paginate = 50
timezone = "Europe/Berlin"
titlecasestyle = "Go"





[languages]

[languages.de]


  disabled = false
  languageCode = 'de-DE'
  languageDirection = 'ltr'
  languageName = 'Deutsch'
  title = "Nicolas Heider - Technischer Designer"
  weight = 0


  [[languages.de.menu.main]]

    name = "Kontakt"
    url = "/"
    weight = 10

  [[languages.de.menu.main]]

    name = "Portfolio"
    url = "/portfolio/"
    weight = 20


  [[languages.de.menu.main]]

    name = "Impressum"
    url = "/imprint/"
    weight = 40




[languages.en]
  disabled = false
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = "English"
  title = "Nicolas Heider - Technical Designer"
  weight = 1


  [[languages.en.menu.main]]

    name = "Contact"
    url = "/en/"
    weight = 10

  [[languages.en.menu.main]]

    name = "Portfolio"
    url = "/en/portfolio/"
    weight = 20


  [[languages.en.menu.main]]

    name = "Imprint"
    url = "/en/imprint/"
    weight = 40




[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noclasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["atom", "html", "json", "rss"]
section = ["atom", "html", "rss"]
taxonomy = ["atom", "html", "rss"]
term = ["atom", "html", "rss"]

[params.authors.will-faught]
default = false
email = ""
name = ""
url = ""

[params.paige.git]
commit_url = "https://github.com/willfaught/paige/commit/%s"

[[params.paige.feed.atom.authors]]
email = "Nicolas.Heider@example.com"
name = "Nicolas Heider"
url = "https://heider.design"

[params.paige.feed.rss]
managing_editor = "Nicolas.Heider@example.com (Nicolas.Heider)"
web_master = "Nicolas.Heider@example.com(Nicolas.Heider)"

[params.paige.file_link]
content = "Edit this page"
disable = true
url = ""